ReactTestApp-DevSupport.podspec

Xcode picks the wrong scheme because there are two ReactTestApp schemes:
One is the test app itself (which we want), and the other is the Pod
that only contains public interfaces. The latter will eventually be
superseded by using native modules but for now, we will rename it to
avoid confusing Xcode.

iOS: Fix test action picking the wrong scheme

---

android/app/src/main/java/com/sample/react/TestAppReactNativeHost.kt
test-app.gradle

When serving assets only through the dev server, resource folders are not generated. This PR enables the dev server flow by making the resource folder to be optional, and copying the manifest file directly from the library root where it is defined to the test app.

Handling cases when dist/res folder is not provided

---

android/app/src/main/java/com/sample/component/ComponentActivity.kt

Override the default behaviour of the `ReactActivity` to support `onBackPressed` events within fragments. This is a temporary solution that will be followed by a proper fix described in: https://github.com/microsoft/react-native-test-app/issues/51

Android: Set the back button behaviour to default

---

yarn.lock

We can't get rid of `minimist@0.0.8` yet because
`@react-native-community/cli` still depends on an older version of
`mkdirp`.

Partially address CVE-2020-7598

---

package.json

Even though Prettier supports YAML files, ESLint doesn't. This simply
generates warnings during CI builds.

Don't run ESLint on YAML files

---

test-app.gradle

Copy the manifest from the project root folder to the generated resources regardless of the res folder generated by bundler.

fix(android): copy the manifest file on android regardless of the res folder

---

.github/workflows/build.yml
package.json

Version bump happens at a later stage so running `pod install` before
release only makes the job slower.
This reverts commit b79fcb773f8fa20d32fffafd6d6c09ce6037fc37.

Revert "ci: Update and commit `Podfile.lock` [skip ci] (#85)"

---

ios/test_app.rb

Avoids iOS and macOS projects clashing with each other.

refactor(Pods): Generate projects under platform folder

---

example/macos/Podfile.lock
macos/ReactTestApp/AppDelegate.swift
macos/ReactTestApp/Base.lproj/Main.storyboard

fix(macOS): Present the component immediately if there's only one

---

example/package.json
ios/test_app.rb
ios/use_react_native-0.62.rb
package.json
yarn.lock

Android and iOS on React Native 0.62 both work after this commit. We're
still missing a way for people to enable Flipper (#112) and we're
waiting on RN for macOS to release 0.62.
Resolves #110

Add preliminary support for 0.62

---

android/app/src/main/java/com/sample/react/ReactBundleNameProvider.kt

This will also allow the bundle names being: "index.android.bundle"

Add .bundle extention to valid bundle names

---

android/app/src/main/java/com/sample/react/TestAppReactNativeHost.kt

fix(Android): Prefer dev server if it's running

---

android/app/src/main/java/com/sample/MainActivity.kt

fix(Android): Present the component immediately if there's only one

---

package.json
plopfile.js

Projects that don't care for `react-native-macos` shouldn't have to install it just to run `plop`. Now we should get a warning instead, and none of the macOS specific commands/files:
```
% yarn plop --dest template-example TemplateExample all
yarn run v1.22.4
⠋ [WARN] Cannot find module 'react-native-macos'; skipping macOS target
✔  ++ /.watchmanconfig
✔  ++ /App.js
✔  ++ /app.json
✔  ++ /babel.config.js
✔  ++ /index.js
✔  ++ /metro.config.js
✔  ++ /package.json
✔  ++ /react-native.config.js
✔  ++ /android/gradle/wrapper/gradle-wrapper.jar
✔  ++ /android/gradle/wrapper/gradle-wrapper.properties
✔  ++ /android/gradle.properties
✔  ++ /android/gradlew
✔  ++ /android/gradlew.bat
✔  ++ /android/settings.gradle
✔  ++ /ios/Podfile
```

fix(macOS): macOS target should be optional

---

.github/workflows/build.yml

This should fix builds randomly failing with `Assertion failed:
(!uv__is_closing(handle)), function uv_close, file
../deps/uv/src/unix/core.c, line 113.`

ci: Use Node 12 LTS

---

.rubocop.yml
Gemfile.lock
android/app/build.gradle
android/app/src/flipper/java/com/sample/react/ReactNativeFlipper.kt
android/app/src/main/java/com/sample/react/TestAppReactNativeHost.kt
ios/ReactTestApp.xcodeproj/project.pbxproj
ios/ReactTestApp/ReactInstance.swift
ios/ReactTestApp/ReactTestApp-Bridging-Header.h
ios/test_app.rb
ios/use_react_native-0.60.rb
ios/use_react_native-0.61.rb
ios/use_react_native-0.62.rb
test/test_test_app.rb

Resolves #112
To test these changes, bump to 0.62 and enable Flipper:
```diff
diff --git a/example/android/gradle.properties b/example/android/gradle.properties
index 08bd26e..699258c 100644
--- a/example/android/gradle.properties
+++ b/example/android/gradle.properties
@@ -1,3 +1,5 @@
android.useAndroidX=true
android.enableJetifier=true
+
+FLIPPER_VERSION=0.33.1
diff --git a/example/ios/Podfile b/example/ios/Podfile
index 59f8153..512a835 100644
--- a/example/ios/Podfile
+++ b/example/ios/Podfile
@@ -2,6 +2,7 @@ require_relative '../node_modules/react-native-test-app/test_app.rb'
workspace 'Example.xcworkspace'
+use_flipper!
use_test_app! do |target|
target.tests do
pod 'Example-Tests', :path => '..'
index f245bf9..80824e0 100644 …
```

fix: Allow users to enable Flipper

---

android/app/build.gradle
android/test-app-util.gradle
ios/test_app.rb
ios/use_react_native-0.60.rb
ios/use_react_native-0.61.rb
ios/use_react_native-0.62.rb

Resolves #124
1. On React Native 0.60 and 0.61, Flipper should remain off even if it's been explicitly turned on
2. On React Native 0.62, Flipper should be enabled with the recommended versions if unspecified
3. On React Native 0.62, enabling Flipper with specific versions should override the recommended versions
4. On React Native 0.62, it is possible to disable Flipper by specifying `false`, i.e. `FLIPPER_VERSION=false` or `use_flipper!(false)`

fix: Enable Flipper by default when on 0.62+

---

ios/test_app.rb

1. Bump to 0.62
```diff
index f245bf9..80824e0 100644
@@ -17,9 +17,8 @@
-    "react": "16.9.0",
-    "react-native": "0.61.5",
-    "react-native-macos": "0.61.39",
+    "react": "16.11.0",
+    "react-native": "0.62.2",
"react-native-test-app": "../"
}
}
```
2. Run `yarn && pod install --project-directory=ios`
3. Observe that Flipper gets included
4. Disable Flipper
```diff
diff --git a/example/ios/Podfile b/example/ios/Podfile
index 59f8153..953899c 100644
--- a/example/ios/Podfile
+++ b/example/ios/Podfile
@@ -2,6 +2,7 @@ require_relative '../node_modules/react-native-test-app/test_app.rb'
workspace …
```

fix(iOS): Flipper is still built when disabled

---

ios/ReactTestApp.xcodeproj/project.pbxproj

Without this, Xcode will consistently crash when trying to expand project configuration, e.g. `Release` as in the screenshot below.
Others seem to have hit this issue as well: https://developer.apple.com/forums/thread/130202

chore(iOS): Remove traces of CocoaPods from source Xcode project

---

example/ios/Podfile.lock
ios/ReactTestApp/Info.plist
ios/test_app.rb

As documented here: https://github.com/AzureAD/microsoft-authentication-library-for-objc#ios-only-steps

fix(iOS): Add URI schemes to support MSAL

---

.github/workflows/build.yml

It's not enabled on _template_ builds (yet), but will at least ensure that the last build job doesn't fail on some random network failure during install.
**Bonus:** It's actually faster in some cases too. Compared to a  [random build](https://github.com/microsoft/react-native-test-app/runs/841420113?check_suite_focus=true):
| Build | Before | After |
|:-|-:|-:|
| lint + test | 3m 26s | 52s |
| iOS | 9m 8s | 6m 19s |
| Android (macos-latest) | 6m 9s | 4m 59s |
| Android (windows-latest) | 8m 28s | 7m 27s |
| macOS | 8m 20s | 6m 47ms |
| release | 1m 26s | 27s |

ci: Cache node_modules folder to reduce hitting ESOCKETTIMEDOUT

---

android/app/build.gradle
android/test-app-util.gradle
ios/test_app.rb

Resolves #140 
1. Apply the patch below
2. Build Android/iOS/macOS apps
3. Verify that the application/bundle id is set to `com.contoso.MyTestApp`
```diff
diff --git a/example/android/gradle.properties b/example/android/gradle.properties
index 08bd26e..02b8080 100644
--- a/example/android/gradle.properties
+++ b/example/android/gradle.properties
@@ -1,3 +1,5 @@
android.useAndroidX=true
android.enableJetifier=true
+
+TEST_APP_IDENTIFIER=com.contoso.MyTestApp
diff --git a/example/ios/Podfile b/example/ios/Podfile
index 59f8153..72aec64 100644
--- a/example/ios/Podfile
+++ b/example/ios/Podfile
@@ -1,6 +1,7 @@
require_relative '../node_modules/react-native-test-app/test_app.rb'
workspace 'Example.xcworkspace'
+test_app_bundle_identifier 'com.contoso.MyTestApp'
use_test_app! do |target| …
```

fix: Support custom application identifier

---

ios/test_app.rb

Changed from `:search_paths` to `:complete` so React binaries are also linked with the test targets. Otherwise, tests targets will fail to link due to missing symbols.

fix(iOS): Tests fail to compile when Flipper is enabled

---

.eslintrc.json
example/App.js
example/index.js
package.json
yarn.lock

`react-native-windows` doesn't have `react-native/template/App`. It's
also not a public API so we shouldn't have used it in the first place.

refactor: Copy the new app template so we can test React Native for Windows

---

windows/ReactTestApp/MainPage.cpp
windows/ReactTestApp/Manifest.cpp
windows/ReactTestApp/Manifest.h
windows/ReactTestApp/ReactTestApp.vcxproj

Reuse the iterator returned by `nlohmann::json::find()` and avoid
performing another lookup.
Also bump target platform minimum version to 10.0.17763.0 so we don't
get warnings on `MenuBar` and `MenuBarItem`.

refactor: Reuse result element when parsing manifest

---

ios/test_app.rb
ios/use_react_native-0.60.rb
ios/use_react_native-0.61.rb

`react-native-macos` does not depend on `react-native` so their version numbers need not be in sync.
The issue manifests itself when you have a project like below:
```
project
├── ios
├── macos
└── node_modules
├── react-native@0.62
└── react-native-macos@0.61
```
In this case, `test_app.rb` will import `use_react_native-0.62.rb` for both iOS and macOS targets. In the latter case, it will fail since 0.61 is installed.

fix(macOS): `pod install` fails when `react-native` version differs

---

.github/workflows/build.yml
example/yarn.lock
yarn.lock

We run `yarn` during template builds in order to install and run Plop.
Caching `/node_modules` will save us a few minutes.

ci: Cache root node_modules during template builds

---

.github/workflows/build.yml
yarn.lock

Bug Fixes
* Handle diffs that were piped to `diff` ([1ecb8a0](https://github.com/tido64/suggestion-bot/commit/1ecb8a09f2f7f097d89204c68b3062200e6bbc80))
* Convert Windows paths to POSIX ([5b711ab](https://github.com/tido64/suggestion-bot/commit/5b711abb05183d99270348048dda37085eea4f1c))
* Don't pack mocks and coverage files ([bcd4915](https://github.com/tido64/suggestion-bot/commit/bcd4915aff70c6d1d2685e089602d82ab10d0c5e))
* Add support for piped input ([16c7a2e](https://github.com/tido64/suggestion-bot/commit/16c7a2ed5a0c3e4253a43b9ab8d489300b4fbd87))
* Add usage message ([f3ddadc](https://github.com/tido64/suggestion-bot/commit/f3ddadcc488fe0d4ac650a0b3a5aeb72a8cb30cb))

chore: Bump suggestion-bot to 1.0.8

---

.gitignore
android/app/build.gradle

Android build artifacts are currently output under `node_modules/react-native-test-app/android`. In a
[monorepo](https://github.com/microsoft/react-native-test-app/wiki#folder-structures), multiple packages can share the same installation if it was hoisted, e.g.:
```
my-monorepo
├── node_modules
│   └── react-native-test-app
│       └── android  # Used by both packages
├── package.json
└── packages
├── my-awesome-component-android
│   ├── build.gradle
│   ├── package.json
│   ├── settings.gradle
│   └── src
└── my-second-awesome-component-android
├── build.gradle
├── package.json
├── settings.gradle
└── src
```
In this example, `node_modules/react-native-test-app/android` may contain build artifacts from both `my-awesome-component-android` and `my-second-awesome-component-android`. …

fix(Android): Android build artifacts pollute installation folder

---

package.json

It's perfectly fine to not have `react-native-macos` installed when one is only concerned with Android and iOS. This change makes `react-native-macos` optional.
See also [peerDependenciesMeta](https://classic.yarnpkg.com/en/docs/package-json#toc-peerdependenciesmeta).
Apply the patch and run `yarn`:
```diff
index 29f2c78..e2ffb97 100644
@@ -19,7 +19,6 @@
"react": "16.9.0",
"react-native": "0.61.5",
-    "react-native-macos": "0.61.39",
"react-native-test-app": "../"
}
}
```
```
% yarn
yarn install v1.22.4
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > react-native-test-app@0.0.1-dev" has unmet peer …
```

fix: unmet peer dependency warning when react-native-macos is missing

---

android/app/src/main/java/com/react/testapp/component/ComponentActivity.kt
android/app/src/main/java/com/react/testapp/react/TestAppReactNativeHost.kt

It doesn't seem like it's necessary to override `ReactActivity#onBackPressed()` any longer. `DefaultHardwareBackBtnHandler#invokeDefaultOnBackPressed()` is called after JS has had its chance to handle the back button event.

fix(Android): Let JS component handle back button first

---

ReactTestApp-DevSupport.podspec
example/Example-Tests.podspec
example/ios/ExampleTests/DevSupportTests.m
example/ios/Podfile.lock
example/macos/Podfile.lock
ios/ReactTestApp/ReactTestApp-DevSupport.m
ios/ReactTestApp/UIViewController+ReactTestApp.m

The symbols declared in ReactTestApp-DevSupport aren't compiled in the same module, but in the main ReactTestApp module. This causes tests to fail building because the linker cannot find the symbols, e.g.:
```
Undefined symbols for architecture x86_64:
"_ReactTestAppSceneDidOpenURLNotification", referenced from:
-[ADALTokenBroker init] in libReactTestApp-Contoso.a(ADALTokenBroker.o)
"_ReactTestAppDidInitializeNotification", referenced from:
+[ADALTokenBroker load] in libReactTestApp-Contoso.a(ADALTokenBroker.o)
+[ReactBootstrapper load] in libReactTestApp-Contoso.a(ReactBootstrapper.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

fix(Apple): Fix tests depending on ReactTestApp-DevSupport not building

---

.github/workflows/build.yml

CI builds randomly fail with `Assertion failed: (!uv__is_closing(handle)), function uv_close, ...`. Adding simple retry logic to work around the issue.
Resolves #156
I don't know what triggers the assertion so I just re-ran the jobs until one failed:

ci: Workaround for random assertion failure

---

Brewfile

If you've added both taps, you'll now get this error:
```
% brew bundle
Tapping adoptopenjdk/openjdk
Using clang-format
Using node
Using swiftlint
Using yarn
Error: Cask adoptopenjdk8 exists in multiple taps:
homebrew/cask-versions/adoptopenjdk8
adoptopenjdk/openjdk/adoptopenjdk8
Installing adoptopenjdk8 has failed!
Homebrew Bundle failed! 1 Brewfile dependency failed to install.
```
Replacing `adoptopenjdk/openjdk` with `homebrew/cask-versions` fixes the
issue for future contributors. Existing contributors need to also run
`brew untap adoptopenjdk/openjdk`.

chore(deps): `adoptopenjdk8` has been moved to `homebrew/cask-versions`

---

android/app/src/main/java/com/react/testapp/react/ReadableMapExt.kt

`WritableArray#pushArray`/-`Map` and `WritableMap#putArray`/-`Map`
changed from mutable to immutable types in 0.61.

fix(Android): Test app fails to build with RN 0.60

---

macos/ReactTestApp/AppDelegate.swift

Ctrl+Shift+0 is used to switch between input languages on Windows. We
change the macOS implementation so they are aligned.

fix(macOS): Enumerate components starting from 1

---

ios/ReactTestApp/React+Compatibility.m
ios/pod_helpers.rb
ios/test_app.rb
ios/use_react_native-0.62.rb

1. Apply the patch below
2. Build the macOS test app
3. Observe that it says "Engine: Hermes" in the upper right corner
```diff
index d6e372a..3cf758b 100644
@@ -16,10 +16,11 @@
},
+    "hermes-engine-darwin": "^0.4.3",
-    "react": "16.9.0",
-    "react-native": "0.61.5",
-    "react-native-macos": "0.61.39",
+    "react": "16.11.0",
+    "react-native": "0.62.2",
+    "react-native-macos": "0.62.1",
"react-native-test-app": "../"
}
}
diff --git a/package.json b/package.json
index ff3b258..e2e0c11 100644
--- a/package.json
+++ b/package.json
@@ -33,9 +33,9 @@
"dependencies": { …
```

fix(macOS): Enable Hermes if hermes-engine-darwin is installed

---

example/yarn.lock
package.json
yarn.lock

Bumps `dot-prop` to 4.2.1 and 5.2.0.
See https://github.com/advisories/GHSA-ff7x-qrg7-qggm for more details.

chore: Address CVE-2020-8116

---

android/app/build.gradle
android/app/src/main/java/com/react/testapp/MainActivity.kt
android/app/src/main/java/com/react/testapp/react/TestAppReactNativeHost.kt

If there is only one component, we navigate to it regardless of whether React Native was successfully initialized. This dismisses any RedBox instances, making it hard to debug errors.

fix(Android): RedBox is dismissed on app start

---

.github/workflows/build.yml
.gitignore
.npmignore
.yarnrc
.yarnrc-offline
example/.yarnrc
example/.yarnrc-offline
example/package.json
example/yarn.lock
package.json
plopfile.js
scripts/install-test-template.sh
yarn.lock

The cache of `node_modules` folder can get stale if changes to `react-native-test-app` was made after the cache has been updated, e.g. when iterating on a PR.
This change also bumps several packages to bust the cache, addressing [CVE-2020-15168](https://github.com/advisories/GHSA-w7rc-rwvf-8q5r), and switches npm registry to https://registry.npmjs.org.

ci: Fix node_modules cache sometimes get stale

---

example/package.json
example/windows/ReactTestAppTests/ManifestTests.cpp
package.json
plopfile.js
windows/ReactTestApp/App.cpp
windows/ReactTestApp/App.h
windows/ReactTestApp/App.xaml
windows/ReactTestApp/MainPage.cpp
windows/ReactTestApp/MainPage.h
windows/ReactTestApp/MainPage.idl
windows/ReactTestApp/Manifest.cpp
windows/ReactTestApp/Manifest.h
windows/ReactTestApp/Package.appxmanifest
windows/ReactTestApp/ReactInstance.cpp
windows/ReactTestApp/ReactInstance.h
windows/ReactTestApp/ReactPackageProvider.cpp
windows/ReactTestApp/ReactPackageProvider.h
windows/ReactTestApp/ReactTestApp.vcxproj
windows/ReactTestApp/ReactTestApp.vcxproj.filters
windows/ReactTestApp/packages.config
windows/ReactTestApp/pch.cpp
windows/ReactTestApp/pch.h
windows/test-app.js
yarn.lock

1. Bump react-native and react-native-windows to 0.63 (see patch below)
2. Build Windows test app
```diff
index 14029ce..4971467 100644
@@ -20,10 +20,9 @@
-    "react": "16.11.0",
-    "react-native": "0.62.2",
-    "react-native-macos": "0.62.1",
+    "react": "16.13.1",
+    "react-native": "0.63.2",
"react-native-test-app": "../",
-    "react-native-windows": "0.62.7"
+    "react-native-windows": "0.63.1"
}
}
```

fix(Windows): Support for 0.63

---

android/app/build.gradle

The wrong version of Hermes can be bundled in the APK if multiple versions are installed and the wrong version is being hoisted. For instance, bumping `react-native` to ^0.63 and keeping `react-native-macos` at ^0.62, will install both `hermes-engine@0.5.1` and `hermes-engine@0.4.3`, where the latter is hoisted. We fix this by using `react-native`'s `node_modules` folder as starting point when looking for `hermes-engine`.
Resolves #207
1. Bump`react-native` to ^0.63 and remove `react-native-windows`
```diff
index b0c89af..99f65f6 100644
@@ -21,10 +21,9 @@
-    "react": "16.11.0",
-    "react-native": "0.62.2",
+ …
```

fix(Android): Wrong version of Hermes is bundled in APK

---

android/react-native-build.gradle
android/test-app-util.gradle
ios/test_app.rb
test/__fixtures__/with_platform_resources/app.json
test/__fixtures__/without_platform_resources/app.json
test/test_test_app.rb

From Expo's documentation:
- [android.package](https://docs.expo.io/versions/v39.0.0/config/app/#package)
- [ios.bundleIdentifier](https://docs.expo.io/versions/v39.0.0/config/app/#bundleidentifier)
- **Android:**
1. Setting `TEST_APP_IDENTIFIER` in `gradle.properties` should output a deprecation warning, but still set `applicationId` correctly
2. Setting `android.package` in `app.json` should correctly set `applicationId`
3. If both are set, the one in `app.json` should take precedence
- **iOS:**
1. Calling `test_app_bundle_identifier()` should output output a deprecation warning, but still set `bundleIdentifier` correctly
2. Setting `ios.bundleIdentifier` in `app.json` should correctly set `bundleIdentifier`
3. If both are set, the one in `app.json` should take precedence
- **macOS:** …

fix: Align with Expo's way to set applicationId/bundleIdentifier

---

windows/test-app.js

Of all 0.63 versions, only 0.63.2 currently works as the project file has hard-coded paths to `.targets` files.
1. Bump `react-native` and `react-native-windows` to latest 0.63 (see patch)
2. Build Example app
```diff
index 5bde75f..c7d8ce9 100644
@@ -25,10 +25,9 @@
-    "react": "16.11.0",
-    "react-native": "0.62.2",
-    "react-native-macos": "0.62.14",
+    "react": "16.13.1",
+    "react-native": "0.63.3",
"react-native-test-app": "../",
-    "react-native-windows": "0.62.12"
+    "react-native-windows": "0.63.3"
}
}
```

fix(Windows): Don't hard-code paths to project files

---

plopfile.js
react-native.config.js
scripts/install-test-template.sh

Adds new `init-test-app` command to React Native CLI
```
% yarn react-native init-test-app --help
react-native init-test-app
Initializes a new test app project
Options:
--destination [string]  Path to the directory where the test app should be created (default: ".")
--name [string]         Display name of the test app (default: "example-test-app")
--platform [string]     Specific platform to support: all, android, ios, macos, windows (default: "all")
-h, --help              output usage information
```

fix: React Native CLI plugin

---

example/macos/Podfile.lock
ios/test_app.rb
test/__fixtures__/with_platform_resources/app.json
test/test_test_app.rb

**Objective**
To support scenarios where there is custom react-native fork, we need to have configurable way to get react-native path.
**Changes**
We have added a new property in platform specific configuration in `manifest.json`, similar to `bundleIdentifier`.
```
{
"name": "Example",
"displayName": "Example",
"components": [
{
"appKey": "Example",
"displayName": "App"
}
],
"macos": {
"bundleIdentifier": "..."
"reactNativePath": "react-native-macos"
}
}
```
If the **app manifest** has the property `reactNativePath`, we will use that as react-native path, else we fallback to default value.

React Native Path from Manifest

---

.vscode/c_cpp_properties.json
.vscode/settings.json
test/getPackageVersion.test.js
test/getVersionNumber.test.js
windows/ReactTestApp/MainPage.cpp
windows/ReactTestApp/MainPage.h
windows/ReactTestApp/MainPage.xaml
windows/ReactTestApp/Package.appxmanifest
windows/ReactTestApp/ReactInstance.cpp
windows/ReactTestApp/ReactInstance.h
windows/ReactTestApp/ReactTestApp.vcxproj
windows/test-app.js

| Normal | With Access Keys |
|-|-|
| ![image](https://user-images.githubusercontent.com/4123478/95022067-219fe780-0675-11eb-8c6c-e1228ff52593.png) | ![image](https://user-images.githubusercontent.com/4123478/95022077-311f3080-0675-11eb-83bb-e9f9afa3aa29.png) |
| ![image](https://user-images.githubusercontent.com/4123478/95021668-a806fa00-0672-11eb-94d0-c3beeb798aae.png) | ![image](https://user-images.githubusercontent.com/4123478/95021711-f0261c80-0672-11eb-9c12-f64f5fc76f82.png) |
1. Build and run Windows test app
2. The debug menu should be **disabled**
- `Ctrl`+`Shift`+`D` should open `react-native-windows`' developer menu
3. Run `git clean -dfqx` to restore state
4. Bump `react-native` to ^0.63 and `react-native-windows` to ^0.63.5 (see diff below)
5. Build and run Windows test app …

fix(Windows): Debug settings are not persisted across sessions

---

ios/test_app.rb

Newer React Native versions have incomplete nullability annotations,
causing build errors when -Wall is enabled. This change disables these
annotation warnings for the React pods.

fix: Suppress nullability-completeness for React

---

.github/swiftformat.json
.github/workflows/build.yml
.swiftlint.yml
Brewfile
ios/ReactTestApp/AppDelegate.swift
ios/ReactTestApp/ContentView.swift
ios/ReactTestApp/Manifest.swift
ios/ReactTestApp/ReactInstance.swift
ios/ReactTestApp/SceneDelegate.swift
macos/ReactTestApp/AppDelegate.swift
macos/ReactTestApp/ViewController.swift
package.json

Adds a new command, `format:swift`, to format Swift files using SwiftFormat so we no longer have to discuss how to format Swift files. It is also added to the CI so we can get annotations in code review.
See also ADO-364860.
- I deliberately put in something that SwiftFormat should trigger on. [Update: Screenshot posted below.]
- The code is formatted but shouldn't change anything functionally. All CI should still pass.

chore(Apple): Use SwiftFormat

---

.github/workflows/build.yml

Windows CI is failing due to a security vulnerability in the `add-path` command used by `microsoft/setup-msbuild`. This is addressed in the latest version.
```
Run microsoft/setup-msbuild@v1.0.1
with:
C:\ProgramData\Chocolatey\bin\vswhere.exe -products * -requires Microsoft.Component.MSBuild -property installationPath -latest
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise
Error: Unable to process command '::add-path::C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin' successfully.
Error: The `add-path` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: …
```

ci(Windows): Bump microsoft/setup-msbuild to address security vulnerability

---

.github/workflows/build.yml

Node 14 is LTS as of [14.15.0](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V14.md#2020-10-27-version-14150-fermium-lts-richardlau). Bumping CI builds to use latest LTS.

ci: Bump Node to 14

---

.vscode/settings.json
windows/ReactTestApp/MainPage.cpp
windows/ReactTestApp/MainPage.h
windows/ReactTestApp/ReactInstance.cpp
windows/ReactTestApp/ReactInstance.h

The test app on Windows doesn't render anything when loading the embedded JS bundle due to incompatible settings. This change ensures that those settings can not be enabled while the embedded bundle is loaded.
ADO-367196
1. Build the test app for Windows
```sh
cd example
yarn
yarn build:windows
yarn install-windows-test-app
```
2. Run the test app without the dev server
3. Try switching between embedded and dev server
4. Run the test app with the dev server (`yarn start:windows`)
5. Try switching between embedded and dev server
| Before | After |
|:-:|:-:|
| ![image](https://user-images.githubusercontent.com/4123478/100025294-c83c7500-2de8-11eb-949a-f4f7bc778d7e.png) | ![image](https://user-images.githubusercontent.com/4123478/100025178-8b707e00-2de8-11eb-88f1-427 …

fix(Windows): Test app fails to load embedded JS bundle

---

windows/test-app.js

If you follow the [instructions](https://github.com/microsoft/react-native-test-app#developing-react-native-test-app) for developing React Native Test App on Windows, `yarn install-windows-test-app` will fail because of the `yarn link` step:
```
$ yarn install-windows-test-app
yarn run v1.22.5
$ D:\Source\react-native-test-app\example\node_modules\.bin\install-windows-test-app
internal/modules/cjs/loader.js:883
throw err;
^
Error: Cannot find module 'yargs'
Require stack:
- D:\Source\react-native-test-app\windows\test-app.js
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
at Function.Module._load (internal/modules/cjs/loader.js:725:27)
at Module.require (internal/modules/cjs/loader.js:952:19)
at require (internal/modules/cjs/helpers.js:88:18)
at …
```

fix(Windows): `install-windows-test-app` fails with yarn link

---

example/windows/ReactTestAppTests/ReactTestAppTests.vcxproj
windows/ReactTestApp/ReactTestApp.vcxproj

[Referencing React Native Windows in your Project](https://microsoft.github.io/react-native-windows/docs/native-modules-setup#cwinrt) now recommends using `SolutionDir` instead of  `MSBuildThisFileDirectory`. Updated our `.vcxproj` files accordingly.

chore(Windows): Resolve paths from SolutionDir instead

---

android/app/build.gradle

Gradle is complaining about `kotlin-android-extensions` being deprecated. It doesn't look like we're using it so I removed it.
Android CI should pass.

fix(Android): Remove deprecated `kotlin-android-extensions` plugin

---

ios/ReactTestApp.xcodeproj/project.pbxproj
ios/ReactTestApp/ReactInstance.swift
macos/ReactTestApp.xcodeproj/project.pbxproj

`RCTTurboModuleLookupDelegate` was renamed in RN 0.64 but we don't really use it so we're removing it before it causes trouble.
iOS and macOS CI should pass.

chore(Apple): Remove unused RCTTurboModuleLookupDelegate implementation

---

android/app/build.gradle
android/app/src/main/java/com/microsoft/reacttestapp/MainActivity.kt
android/app/src/main/java/com/microsoft/reacttestapp/component/ComponentBottomSheetDialogFragment.kt
android/app/src/main/java/com/microsoft/reacttestapp/component/ComponentViewModel.kt
android/app/src/main/java/com/microsoft/reacttestapp/manifest/Manifest.kt
example/.gitignore
example/app.json
example/ios/ExampleTests/ManifestTests.swift
ios/ReactTestApp/ContentView.swift
ios/ReactTestApp/Manifest.swift
macos/ReactTestApp/AppDelegate.swift
windows/ReactTestApp/MainPage.cpp
windows/ReactTestApp/MainPage.xaml
windows/ReactTestApp/Manifest.cpp
windows/ReactTestApp/Manifest.h

Adds support for specifying presentation style in `app.json`. Only modal is implemented in this PR.
1. Build Example app
2. Launching "App" should open the example app as usual
3. Launching "App (modal)" should open the example app in a modal dialog/window
4. Repeat steps 1-3 for each platform
| Android | iOS | macOS | Windows |
|:-:|:-:|:-:|:-:|
| ![Screenshot_1607199618](https://user-images.githubusercontent.com/4123478/101262528-ce631780-373f-11eb-8035-b6d7d3d00be0.png) | ![image](https://user-images.githubusercontent.com/4123478/101262272-ab376880-373d-11eb-963c-c56ae5c9a53b.png) | <img width="776" alt="image" src="https://user-images.githubusercontent.com/4123478/101262392-ab843380-373e-11eb-9bc3-fc0ecb0344e4.png"> | ![image](https://user-images.githubusercontent.com/4123478/101261986 …

fix: Support for specifying presentation style

---

.github/workflows/build.yml

An access token is automatically created for a workflow. It should have enough permissions for our needs. See [Authentication in a workflow](https://docs.github.com/en/free-pro-team@latest/actions/reference/authentication-in-a-workflow).
- A comment should be posted to suggest a fix for a formatting issue
- CI should pass.

ci: Use the automatically generated access token

---

ios/ReactTestApp.xcodeproj/project.pbxproj
ios/ReactTestApp/RCTDevSupport+UIScene.m
ios/ReactTestApp/React+Compatibility.h
ios/ReactTestApp/React+Compatibility.m
macos/ReactTestApp.xcodeproj/project.pbxproj

This change monkey patches React Native on versions prior to 0.63.2 to
fix a bug with images not rendering when on iOS 14.
See https://github.com/facebook/react-native/pull/29420.
1. Downgrade Example app to 0.62
```diff
index 351eac3..3a1bff6 100644
@@ -24,10 +24,10 @@
-    "react": "16.13.1",
-    "react-native": "0.63.3",
-    "react-native-macos": "0.63.1",
+    "react": "16.11.0",
+    "react-native": "0.62.2",
+    "react-native-macos": "0.62.16",
"react-native-test-app": "../",
-    "react-native-windows": "0.63.10"
+    "react-native-windows": "0.62.17"
}
}
```
2. Delete `/example/ios/Podfile.lock` before …

fix(iOS): Images don't render on iOS 14 with RN < 0.63.2

---

.rubocop.yml
ios/test_app.rb
ios/use_react_native-0.60.rb
ios/use_react_native-0.61.rb
ios/use_react_native-0.62.rb
ios/use_react_native-0.63.rb
macos/test_app.rb
package.json
scripts/set-react-version.js
test_app.rb

Allow options to be passed directly to `use_react_native!`, such as `:hermes_enabled` introduced in 0.64:
```rb
use_test_app! :hermes_enabled => true
```
1. Navigate to `/example`
2. Delete `ios/Podfile.lock` and `ios/Pods/`
3. Run `yarn`
4. Run `pod install --project-directory=ios`
5. Build `ios/Example.xcworkspace`
6. Repeat steps 1-6 for versions 0.60, 0.61, 0.62, 0.63
- Use `yarn set-react-version` to set the correct package versions

fix(Apple): Allow passing options to use_react_native!

---

android/app/build.gradle
android/app/src/main/java/com/microsoft/reacttestapp/MainActivity.kt
android/app/src/main/java/com/microsoft/reacttestapp/Session.kt
android/app/src/main/java/com/microsoft/reacttestapp/component/ComponentListAdapter.kt
android/app/src/main/java/com/microsoft/reacttestapp/manifest/ManifestProvider.kt
android/app/src/main/res/menu/top_app_bar.xml
android/app/src/main/res/values/strings.xml
example/ios/ExampleTests/ManifestTests.swift
example/windows/ReactTestAppTests/ManifestTests.cpp
ios/ReactTestApp.xcodeproj/project.pbxproj
ios/ReactTestApp/ContentView.swift
ios/ReactTestApp/Manifest.swift
ios/ReactTestApp/ReactInstance.swift
ios/ReactTestApp/Session.swift
macos/ReactTestApp.xcodeproj/project.pbxproj
macos/ReactTestApp/AppDelegate.swift
macos/ReactTestApp/Base.lproj/Main.storyboard
windows/ReactTestApp/MainPage.cpp
windows/ReactTestApp/MainPage.h
windows/ReactTestApp/MainPage.xaml
windows/ReactTestApp/Manifest.cpp
windows/ReactTestApp/Manifest.h
windows/ReactTestApp/ReactTestApp.vcxproj
windows/ReactTestApp/ReactTestApp.vcxproj.filters
windows/ReactTestApp/Session.h

Adds a toggle to reopen the component that was last opened in previous session.
1. Build and run Example app
2. Note that we are seeing a blank window on desktop, and the component list on mobile
3. Enable _Remember last opened component_ (see screenshots below)
4. Open any component
5. Restart Example app
6. The component that was opened last session should now be reopened
7. Disable _Remember last opened component_
8. Restart Example app
9. We should now see either a blank window or the component list
10. Repeat steps 1-9 for all platforms
| Android | iOS | macOS | Windows |
|:-:|:-:|:-:|:-:|
| ![image](https://user-images.githubusercontent.com/4123478/102710441-9e288680-42b2-11eb-9847-f124583f9260.png) | ![Simulator Screen Shot - iPhone 12 Pro - 2020-12-20 at 11 00 …

fix: Open last component from previous session

---

ios/ReactTestApp/RCTDevSupport+UIScene.m

A monkey-patch for RedBox not displaying on iOS 13+ was added some time
ago but stopped working in 0.62 because the method signature had
changed.
1. `yarn set-react-version 0.61`
2. Build and run Example app
3. Make a change that causes a RedBox to appear, e.g.:
```diff
diff --git a/example/App.js b/example/App.js
index 8cfe754..442ee32 100644
--- a/example/App.js
+++ b/example/App.js
@@ -69,6 +69,7 @@ const App = () => {
return (
<SafeAreaView style={backgroundStyle}>
+      fail
<StatusBar barStyle={isDarkMode ? "light-content" : "dark-content"} />
<ScrollView
contentInsetAdjustmentBehavior="automatic"
```
4. Hit "Dismiss" to make sure RedBox can be dismissed
4. Repeat steps 1-4 for versions 0.62 and 0.63

fix(iOS): Monkey-patch RedBox not displaying on 0.62

---

example/ios/Podfile.lock
example/macos/Podfile.lock
macos/ReactTestApp/AppDelegate.swift

`-[RCTRootView minimumSize]` wasn't added until [0.63](https://github.com/facebook/react-native/commit/432868b0c0c591c245a9cdb91201c64aa5bd70c6):
```
/Users/runner/work/async-storage/async-storage/node_modules/.generated/macos/ReactTestApp/AppDelegate.swift:155:26: error: value of type 'RCTRootView' has no member 'minimumSize'
rootView.minimumSize = WindowSize.modalSize
~~~~~~~~ ^~~~~~~~~~~
```
Instead, we will set the frame size when the view is presented.
Resolves #268.
1. `yarn set-react-version 0.62`
2. Build Example app
3. Open Example app and make sure "App (modal)" works
4. `yarn set-react-version 0.63`
5. Repeat steps 2-3

fix(macOS): RCTRootView.minimumSize doesn't exist before 0.63

---

ios/ReactTestApp/React+Compatibility.m

`react-native-test-app` fails to build due to a nullability-completeness warning in `RCTAnimatedImage.h`.
Build Example iOS app in Release mode (Product > Build For > Profiling ⇧⌘I)

fix(iOS): Ignore nullability-completeness warning in RCTAnimatedImage.h

---

ios/ReactTestApp/ReactInstance.swift

`SKDescriptorMapper` was initialized without defaults, breaking the
Layout and Logs plugins in Flipper.

fix(iOS): Correctly initialize Flipper with defaults

---

windows/test-app.js

The app solution template provided by `react-native-windows` currently assumes that `react-native-windows` is always installed in `..\node_modules\react-native-windows`.
Currently breaks AsyncStorage: https://github.com/react-native-async-storage/async-storage/pull/524/checks?check_run_id=1758514238
The patch has been verified to work locally.

fix(Windows): hard-coded react-native-windows path in .sln

---

android/app/build.gradle
android/app/src/main/java/com/microsoft/reacttestapp/TestApp.kt
android/app/src/main/java/com/microsoft/reacttestapp/react/TestAppReactNativeHost.kt
android/build.gradle
android/dependencies.gradle
android/react-native-build.gradle
android/settings.gradle
android/support/build.gradle
android/support/src/main/AndroidManifest.xml
android/support/src/main/java/com/microsoft/reacttestapp/ReactTestAppLifecycleEvents.java
android/support/src/main/java/com/microsoft/reacttestapp/support/ReactTestAppLifecycleEvents.java
example/android/build.gradle
example/ios/ExampleTests/DevSupportTests.m
ios/ReactTestApp/AppDelegate.swift
ios/ReactTestApp/Public/ReactTestApp-DevSupport.h
ios/ReactTestApp/ReactInstance.swift
ios/ReactTestApp/ReactTestApp-DevSupport.m
plopfile.js
test-app.gradle

This PR adds a mechanism for listening lifecycle events such as application start, RN init, etc. It does it by looking-up methods in ReactPackage's provided by native modules using reflection.
The issue #145 is somewhat relevant, but doesn't address the exact problem.
To test this change, you will need to link a native module that has a ReactPackage with one (or all) of the following methods:
```java
public class LpcAndroidTestReactPackage implements ReactPackage, ReactTestAppLifecycleEvents {
@Override
public void onTestAppCreated() {
System.out.println("onTestAppCreated()");
}
@Override
public void onPreInitReactNativeInstance() {
System.out.println("onPreInitReactNativeInstance()");
}
...
}
```

A mechanism for listening to lifecycle events in RNTA

---

Gemfile
Gemfile.lock

```
$ bundle exec rubocop
Inspecting 15 files
...............
15 files inspected, no offenses detected
Tip: Based on detected gems, the following RuboCop extension libraries might be helpful:
* rubocop-minitest (http://github.com/rubocop-hq/rubocop-minitest)
You can opt out of this message by adding the following to your config (see https://docs.rubocop.org/rubocop/extensions.html#extension-suggestions for more options):
AllCops:
SuggestExtensions: false
```
CI should be green.

ci: use rubocop-minitest as suggested by RuboCop

---

yarn.lock

This doesn't really affect published packages (hence the chore tag) but it's good to not have it regardless.
For more details, see: https://github.com/advisories/GHSA-4r62-v4vq-hr96

chore: address CVE-2021-21306

---

android/app/build.gradle
android/build.gradle
android/dependencies.gradle
android/support/build.gradle
example/android/gradle.properties
example/android/gradle/wrapper/gradle-wrapper.properties
example/android/settings.gradle
scripts/set-react-version.js
test-app.gradle

When building react-native from source, `react-native-codegen` also needs to be included.
Even with this fix, building will still fail due to `react-native-codegen` being out of sync with `react-native#master`:
```
> Task :ReactAndroid:buildReactNdkLib FAILED
make: Entering directory `~/Source/react-native-test-app/example/node_modules/react-native/ReactAndroid/src/main/jni/react/jni'
make: Leaving directory `~/Source/react-native-test-app/example/node_modules/react-native/ReactAndroid/src/main/jni/react/jni'
~/Library/Android/sdk/ndk/20.1.5948944/build/core/build-binary.mk:666: Android NDK: Module react_codegen_rncore depends on undefined modules: react_render_components_view
~/Library/Android/sdk/ndk/20.1.5948944/build/core/build-binary.mk:679: *** Android NDK: Aborting (set …
```

fix(android): include missing `react-native-codegen`

---

ios/ReactTestApp/ContentView.swift

Background colour of `RCTRootView` is [always white](https://github.com/facebook/react-native/blob/master/React/Base/RCTRootView.m#L61), even when in dark mode. This issue does not repro on macOS because a background colour is [never set](https://github.com/microsoft/react-native-macos/blob/master/React/Base/RCTRootView.m#L81).
Resolves #285.

fix(ios): background color doesn't respect dark mode

---

.github/workflows/build.yml
example/windows/ReactTestAppTests/ManifestTests.cpp
windows/ReactTestApp/Manifest.cpp

Current working directory when running tests (with `VSTest.Console.exe`) changed between Visual Studio 16.8 and 16.9 and broke our pipelines. To prevent future build failures, we'll use the absolute path to the test source file to build the path to the test fixtures.
Resolves #287.
Windows CI should pass.

fix(windows): unhandled exception thrown in std::_Xlen_string()

---

plopfile.js

Plop is trying to replace values between `{{` and `}}` even though we just want to copy the file verbatim. The real fix here is to replace Plop with something else since we don't really use Handlebar templates for anything, but that will come in a separate PR.
Resolves #290.
1. Checkout this branch and make sure it is clean (i.e. run `yarn clean`)
2. Run `yarn link` to register a link
3. Checkout https://github.com/pruthvip/rnta-test
4. Run the following commands in `rnta-test`:
```sh
yarn
yarn link react-native-test-app
yarn plop --plopfile node_modules/react-native-test-app/plopfile.js --dest test test all
```

fix: work around Plop trying to replace variables in `App.js`

---

.github/workflows/build.yml

Schedule nightly builds against react-native#master to catch build failures earlier.
It doesn't look like you can test this so I'll check in the morning after this lands. Regardless, CI should pass.

ci: schedule nightly builds against react-native#master

---

ios/test_app.rb

Adds support for react-native/react-native-macos nightlies/canaries.
1. `yarn set-react-version nightly`
2. Build Example app

fix(apple): add support for nightlies/canaries

---

.github/workflows/build.yml

`nightly` currently doesn't build due to use of version numbers that are incompatible with CocoaPods. See https://github.com/facebook/react-native/issues/30036 and https://github.com/microsoft/react-native-macos/issues/620 for more details.

ci(ios): build nightlies off master

---

.npmignore

Running `yarn configure-test-app --force` fails because `example/android/gradle.properties` is not shipped.

fix(android): configure script cannot find `gradle.properties`

---

.gitignore
android/app/build.gradle
android/build.gradle
android/force-resolve-trove4j.gradle
android/react-native-build.gradle
android/support/build.gradle
example/android/build.gradle
scripts/configure.js
test/configure/__snapshots__/gatherConfig.test.js.snap

JCenter is being sunset: https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

fix(android): migrate away from JCenter

---

.github/workflows/build.yml
example/package.json
example/windows/.gitignore
example/yarn.lock
package.json
scripts/set-react-version.js
test/windows-test-app/generateSolution.test.js
windows/ReactTestApp/ReactTestApp.vcxproj
windows/ReactTestApp/packages.config
windows/test-app.js
yarn.lock

Restores the ability to use the experimental NuGet packages.
Resolves #299.
To test locally, specify the `--use-nuget` flag when installing the Windows test app:
```
cd example
yarn
yarn install-windows-test-app --use-nuget
```

fix(windows): restore ability to use NuGet

---

package.json
scripts/configure.js
test/configure/getAppName.test.js
test/configure/isDestructive.test.js
test/configure/removeAllFiles.test.js
test/configure/updatePackageManifest.test.js
test/configure/writeAllFiles.test.js
test/mockFiles.js
test/windows-test-app/copyAndReplace.test.js
test/windows-test-app/generateSolution.test.js
test/windows-test-app/getBundleResources.test.js
test/windows-test-app/parseResources.test.js
windows/ReactTestApp/App.cpp
windows/ReactTestApp/ReactTestApp.vcxproj
windows/ReactTestApp/ReactTestApp.vcxproj.filters
windows/test-app.js
yarn.lock

Picks up the `Package.appxmanifest` placed next to the generated `.sln`.
Resolves #224.
1. Generate the solution:
```
cd example
yarn
yarn install-windows-test-app
```
2. Observe that `Package.appxmanifest` is the same as the one from `react-native-test-app`.
3. Close Visual Studio.
4. Copy `/windows/ReactTestApp/Package.appxmanifest` ito `/example/windows`
5. Modify `/example/windows/Package.appxmanifest`, e.g. change the display name to `Example`
6. Open `app.json` and add the following:
```diff
diff --git a/example/app.json b/example/app.json
index 8463354..941fa30 100644
--- a/example/app.json
+++ b/example/app.json
@@ -29,5 +29,8 @@
"dist/assets",
"dist/main.windows.bundle"
]
+  },
+  "windows": {
+    "appxManifest": "windows/Package.appxmanifest"
}
}
``` …

fix(windows): support for custom Package.appxmanifest

---

android/support/build.gradle
example/android/build.gradle
test-app.gradle

Fluent UI [broke](https://github.com/microsoft/fluentui-react-native/pull/665) when bumping RNTA, because certain scripts were not linked correctly. Instead of expecting the consumer to link required gradle scripts, we can do it automatically when applying the RNTA plugin. This PR does exactly that.
Automation on CI should be sufficient to pick-up any issues with the build configuration.

fix(android): ensure that RNTA can automatically link gradle scripts

---

example/ios/Podfile
example/ios/Podfile.lock
scripts/configure.js
test/configure/__snapshots__/gatherConfig.test.js.snap

Flipper breaks when built with Xcode 12.5.
1. Update to Xcode 12.5
2. Build Example iOS app

fix(ios): build breaks on Xcode 12.5

---

Gemfile.lock

`rexml` is used in build tools only (hence the **chore** designation).
For more details, see https://nvd.nist.gov/vuln/detail/CVE-2021-28965.

chore: address CVE-2021-28965

---

.github/dependabot.yml

Adds more lock files for Dependabot to manage.
There's nothing to test.

chore: add Gemfile and example/yarn.lock to Dependabot [skip ci]

---

.github/workflows/build.yml

Ensure duplicated packages fail CI.
CI should be green.

ci: deduplicate packages

---

example/ios/Podfile
example/ios/Podfile.lock
example/macos/Podfile.lock

iOS nightly builds are failing due to `Flipper-RSocket` being resolved to a version that depends on a newer version of `Flipper-Folly`:
```
[!] CocoaPods could not find compatible versions for pod "Flipper-Folly":
In snapshot (Podfile.lock):
Flipper-Folly (= 2.5.3, ~> 2.5)
In Podfile:
Flipper-Folly (= 2.5.3)
Flipper-RSocket (= 1.4.3) was resolved to 1.4.3, which depends on
Flipper-Folly (~> 2.6)
FlipperKit/FlipperKitLayoutPlugin (= 0.75.1) was resolved to 0.75.1, which depends on
FlipperKit/Core (= 0.75.1) was resolved to 0.75.1, which depends on
Flipper (~> 0.75.1) was resolved to 0.75.1, which depends on
Flipper-Folly (~> 2.5)
Error: Process completed with exit code 1.
```

chore: pin Flipper-RSocket version to fix iOS nightly builds

---

.github/workflows/build.yml
example/windows/ReactTestAppTests/ReactTestAppTests.vcxproj
ios/ReactTestApp/React+Compatibility.m
scripts/set-react-version.js
test/windows-test-app/getVersionNumber.test.js
windows/ReactTestApp/ReactTestApp.vcxproj
windows/test-app.js

Set up nightly builds against `react-native-macos@canary` and `react-native-windows@canary`.

ci: nightly builds against react-native-macos and -windows canaries

---

example/metro.config.windows.js
windows/ReactTestApp/ReactInstance.cpp

`JavaScriptMainModuleName` was deprecated in 0.64, and removed in https://github.com/microsoft/react-native-windows/commit/22e1206ce28eb55e75af5e7740ef8bb8ad25e183.
Caught with Windows nightly builds: https://github.com/microsoft/react-native-test-app/runs/2855115978?check_suite_focus=true
```sh
yarn clean
yarn set-react-version 0.64
cd example
yarn
yarn build:windows
yarn install-windows-test-app --use-nuget
yarn start:windows
```
Build and run the test app. You should be able to switch between embedded and dev server.

fix(windows): JavaScriptMainModuleName is deprecated

---

example/react-native.config.js
scripts/configure.js

Latest Windows nightly build has revealed a bug in `react-native.config.js`: https://github.com/microsoft/react-native-test-app/runs/2863315020?check_suite_focus=true
```
$ yarn install-windows-test-app --use-nuget
yarn run v1.22.5
$ ~\example\node_modules\.bin\install-windows-test-app --use-nuget
warning: resource with path 'dist/assets' was not found
warning: resource with path 'dist/main.windows.bundle' was not found
× Auto-linking...
Error: Error: ENOENT: no such file or directory, open '~\example\windows\windows\Example.sln'. (317ms)
```

fix(windows): auto-link step fails when running 'install-windows-test-app'

---

react-native.config.js

Due to a recent change in [`@react-native-windows/cli`](https://github.com/microsoft/react-native-windows/commit/11a322b373c28d0e73dde83550dc42cee1352457), `react-native-test-app` is now considered a native module and autolinked.
```sh
yarn set-react-version canary-windows
cd example
yarn
yarn install-windows-test-app --use-nuget
cd windows
nuget restore
```
`nuget restore` should succeed without any errors.

fix(windows): prevent cli from autolinking react-native-test-app

---

windows/ReactTestApp/ReactInstance.cpp

`REACT_NATIVE_VERSION` is 0 for `react-native-windows@canary`.

fix(windows): REACT_NATIVE_VERSION is 0 for canary

---

.github/workflows/build.yml
windows/ReactTestApp/MainPage.cpp
windows/ReactTestApp/MainPage.h
windows/ReactTestApp/ReactInstance.cpp
windows/ReactTestApp/ReactInstance.h

Windows test app crashes when trying to load a JS bundle that doesn't exist.
```sh
cd example
yarn
yarn install-windows-test-app --use-nuget
yarn start:windows
```
When the test app is loaded, try switching to embedded JS bundle.

fix(windows): crash when no JS bundle is found
