microsoft/react-native-test-app

- example/Podfile.lock
- example/app.json
- example/gradle.properties
- plopfile.js
- test-app.gradle
- test/fixtures/with_ios_resources/app.json
- test/fixtures/with_ios_resources/ios/.gitignore
- test/fixtures/without_ios_resources/app.json
- test/fixtures/without_ios_resources/ios/.gitignore
- test/test_test_app.rb
- test_app.rb
* (wip) Forking resources between platforms in the manifest definition
* Loading and copying resources from the manifest on Android
> Loading resources from the manifest on android

- .github/workflows/build.yml
- plopfile.js
> Fix JS bundling in newly generated projects

- android/app/build.gradle
- android/app/src/main/AndroidManifest.xml
- android/app/src/main/java/com/sample/MainActivity.kt
- android/app/src/main/java/com/sample/react/TestAppReactNativeHost.kt
- android/app/src/main/res/layout/activity_main.xml
- android/app/src/main/res/menu/top_app_bar.xml
- android/app/src/main/res/values/strings.xml
- android/app/src/main/res/values/styles.xml
- example/android/build.gradle
Incidentally, this also fixes dev server support.
Resolves #53.
> Android: Add menu for changing JS bundle source

- android/app/src/main/java/com/sample/MainActivity.kt
- android/app/src/main/java/com/sample/TestApp.kt
- android/app/src/main/java/com/sample/component/ComponentActivity.kt
- android/app/src/main/java/com/sample/react/TestAppReactNativeHost.kt
Addresses https://github.com/microsoft/react-native-test-app/issues/66 and fixes the crash when bundle is not present. Also proactively disables the menu item when bundle is not available.
> Refactor the TestAppReactNativeHost

- example/package.json
- ios/ReactTestApp/RCTDevSupport+UIScene.m
- package.json
| Before | After |
|-|-|
| ![Simulator Screen Shot - iPhone 11 Pro - 2020-04-26 at 14 13 11](https://user-images.githubusercontent.com/4123478/80307267-3c1d8d00-87c8-11ea-931f-995ef7b6f74f.png) | ![Simulator Screen Shot - iPhone 11 Pro - 2020-04-26 at 14 12 54](https://user-images.githubusercontent.com/4123478/80307270-417ad780-87c8-11ea-8b48-65c775bc5796.png) |
> fix(iOS): RedBox can sometimes be invisible

- .swiftlint.yml
- android/app/src/main/java/com/sample/MainActivity.kt
- android/app/src/main/java/com/sample/component/ComponentActivity.kt
- android/app/src/main/java/com/sample/manifest/Manifest.kt
- example/app.json
- example/ios/ExampleTests/ManifestTests.swift
- example/ios/Podfile.lock
- ios/ReactTestApp/ContentView.swift
- ios/ReactTestApp/Manifest.swift
- ios/ReactTestApp/ReactInstance.swift
- plopfile.js
- test_app.rb
Implements https://github.com/microsoft/continuity/issues/61#issuecomment-625212973.
> fix: inconsistent component order on home screen

- .github/workflows/build.yml
- .npmignore
- README.md
- ios/test_app.rb
- plopfile.js
> macOS: Add Plop template

- ios/ReactTestApp/ContentView.swift
> fix(iOS): Present the component immediately if there's only one

- example/ios/Podfile.lock
- example/macos/Podfile.lock
- ios/ReactTestApp.xcodeproj/project.pbxproj
- ios/ReactTestApp/React+Compatibility.h
- ios/ReactTestApp/React+Compatibility.m
- ios/ReactTestApp/ReactInstance.swift
- ios/ReactTestApp/ReactTestApp-Bridging-Header.h
- ios/test_app.rb
- macos/ReactTestApp.xcodeproj/project.pbxproj
> fix: Add REACT_NATIVE_VERSION macro for backwards compatibility

- android/app/build.gradle
- android/app/src/androidTest/java/com/react/testapp/ExampleInstrumentedTest.kt
- android/app/src/flipper/java/com/react/testapp/ReactNativeFlipper.kt
- android/app/src/main/AndroidManifest.xml
- android/app/src/main/java/com/react/testapp/MainActivity.kt
- android/app/src/main/java/com/react/testapp/TestApp.kt
- android/app/src/main/java/com/react/testapp/component/ComponentActivity.kt
- android/app/src/main/java/com/react/testapp/component/ComponentListAdapter.kt
- android/app/src/main/java/com/react/testapp/component/ComponentViewModel.kt
- android/app/src/main/java/com/react/testapp/di/ActivityScope.kt
- android/app/src/main/java/com/react/testapp/di/TestAppBindings.kt
- android/app/src/main/java/com/react/testapp/di/TestAppComponent.kt
- android/app/src/main/java/com/react/testapp/manifest/Manifest.kt
- android/app/src/main/java/com/react/testapp/manifest/ManifestModule.kt
- android/app/src/main/java/com/react/testapp/manifest/ManifestProvider.kt
- android/app/src/main/java/com/react/testapp/react/ReactBundleNameProvider.kt
- android/app/src/main/java/com/react/testapp/react/TestAppReactNativeHost.kt
- android/app/src/test/java/com/react/testapp/ExampleUnitTest.kt
Renames the root package and its references from com.sample to com.react.testapp #34
> fix(android): rename the root package from com.sample to com.react.testapp

- example/ios/ExampleTests/ManifestTests.swift
- ios/ReactTestApp/Manifest.swift
- ios/ReactTestApp/RCTDevSupport+UIScene.m
- macos/ReactTestApp/ViewController.swift
> fix(Apple): Complex `initialProperties` may fail the app

- ios/test_app.rb
- test/test_test_app.rb
> fix(Apple): `pod install` fails when `--repo-update` is also specified

- ios/ReactTestApp/ContentView.swift
- ios/ReactTestApp/ReactInstance.swift
| Platform | Components List | Debug Menu |
|-|-|-|
| iOS (device) | ![Simulator Screen Shot - iPhone 11 Pro Max - 2020-07-15 at 02 09 58](https://user-images.githubusercontent.com/4123478/87488329-5f760c80-c640-11ea-9912-c686ada3940f.png) | ![Simulator Screen Shot - iPhone 11 Pro Max - 2020-07-15 at 02 09 55](https://user-images.githubusercontent.com/4123478/87488338-6735b100-c640-11ea-9e04-7072d91a2fe4.png) |
| iOS (simulator) | ![Simulator Screen Shot - iPhone 11 Pro Max - 2020-07-15 at 02 05 55](https://user-images.githubusercontent.com/4123478/87488096-bcbd8e00-c63f-11ea-95c7-e0988e60cf5f.png) | ![Simulator Screen Shot - iPhone 11 Pro Max - 2020-07-15 at 02 05 49](https://user-images.githubusercontent.com/4123478/87488105-c47d3280-c63f-11ea-83b5-511cd8587110.png) |
| macOS | <img …
> fix(Apple): Move bundle options to React debug menu

- android/app/src/main/java/com/react/testapp/MainActivity.kt
- android/app/src/main/java/com/react/testapp/react/TestAppReactNativeHost.kt
| "Shaker" menu | Overflow menu |
|:-:|:-:|
| ![image](https://user-images.githubusercontent.com/4123478/87832555-8a51a200-c886-11ea-9f8a-d465e6c5b678.png) | ![image](https://user-images.githubusercontent.com/4123478/87832872-414e1d80-c887-11ea-90dd-54e89302ed49.png) |
Resolves #119
> fix(Android): Add option to switch bundle source to debug menu

- .github/swiftlint.json
- .github/workflows/build.yml
- Brewfile
- example/ios/ExampleTests/ManifestTests.swift
> ci: Run swiftlint and capture warnings/errors

- .swiftlint.yml
- ios/ReactTestApp/AppDelegate.swift
- yarn.lock
Bug Fixes
- Wrong suggestion for moving a line ([61eb827](https://github.com/tido64/suggestion-bot/commit/61eb827f8273298128a664c6590d341359aad146))
- Don't include tests in the package ([73d7c1c](https://github.com/tido64/suggestion-bot/commit/73d7c1cb583507b5329d5b81d743f47210ba0cc7))
- Skip invalid diffs ([828ca61](https://github.com/tido64/suggestion-bot/commit/828ca619d2f56a2fb25fa61810978da49dfd2d49))
> chore: Bump suggestion-bot to 1.0.3

- android/app/src/main/java/com/react/testapp/component/ComponentActivity.kt
So we can close https://github.com/microsoft/react-native-test-app/issues/51
> Removing a comment

- android/app/src/main/java/com/react/testapp/MainActivity.kt
- android/app/src/main/java/com/react/testapp/component/ComponentActivity.kt
- android/app/src/main/java/com/react/testapp/component/ComponentViewModel.kt
- android/app/src/main/java/com/react/testapp/manifest/Manifest.kt
- android/app/src/main/java/com/react/testapp/manifest/ManifestModule.kt
- android/app/src/main/java/com/react/testapp/manifest/MoshiBundleAdapter.kt
- android/app/src/main/java/com/react/testapp/react/ReadableMapExt.kt
- android/gradle/wrapper/gradle-wrapper.properties
> fix(Android): Complex `initialProperties` may fail the app

- ios/ReactTestApp.xcodeproj/project.pbxproj
- ios/test_app.rb
- macos/ReactTestApp.xcodeproj/xcshareddata/xcschemes/ReactTestApp.xcscheme
- test/__fixtures__/with_resources/app.json
- test/test_test_app.rb
> fix(Apple): Also create an xcscheme to match app name

- .github/workflows/build.yml
- package.json
- yarn.lock
Ensure the first commit message follows [conventional commit format](https://www.conventionalcommits.org/). GitHub reuses the first commit message when merging against `master` so we should make sure `semantic-release` can process it appropriately.
- CI should only fail when the first commit message is wrongly formatted
> ci: Run commitlint to verify commit messages

- .github/ktlint.json
- .github/workflows/build.yml
- Brewfile
- android/app/src/flipper/java/com/microsoft/reacttestapp/ReactNativeFlipper.kt
- android/app/src/main/java/com/microsoft/reacttestapp/MainActivity.kt
- android/app/src/main/java/com/microsoft/reacttestapp/Session.kt
- android/app/src/main/java/com/microsoft/reacttestapp/component/ComponentBottomSheetDialogFragment.kt
- android/app/src/main/java/com/microsoft/reacttestapp/react/TestAppReactNativeHost.kt
- package.json
Run [ktlint](https://ktlint.github.io/) on CI.
1. Run without fixes should report issues.
2. Run with fixes should be green.
> ci: integrate ktlint

- scripts/set-react-version.js
- tsconfig.json
- yarn.lock
Enable type checking of scripts.
> test: enable type checking of scripts

- example/yarn.lock
- yarn.lock
See https://github.com/advisories/GHSA-p9pc-299p-vxgp.
> chore: address prototype pollution in yargs-parser

- .github/dependabot.yml
- example/yarn.lock
- package.json
- yarn.lock
Set up Dependabot to run weekly.
CI should be green.
> chore: set up Dependabot

- .github/dependabot.yml
Let Dependabot update GitHub Actions.
There's nothing to test.
> chore: configure Dependabot for GitHub Actions
